### ISSUE TITLE
Error "java.lang.IllegalArgumentException: Invalid point encoding 0x30"

### ISSUE THREAD

**Issue by duc12597** [wultra/powerauth-server#135]
# Error "java.lang.IllegalArgumentException: Invalid point encoding 0x30"

I'm trying to use the SOAP interface from a Spring client. Everytime I call `client.prepareActivation(prepareReq)`, my IDE returns the `SoapFaultClientException: Invalid input parameter format`: https://gist.github.com/duc12597/84e6707688f2caca9a85241b85e2846f#file-ide_log-txt

Here is the Tomcat log which throws `java.lang.IllegalArgumentException: Invalid point encoding 0x30`: https://gist.github.com/duc12597/84e6707688f2caca9a85241b85e2846f#file-tomcat_log-txt

My system environment:
- JDK 1.8
- Tomcat 9
- `powerauth-java-server`, `powerauth-admin` and `powerauth-restful-server-spring` deployed, all 0.18.0

Here are my [PowerAuthWebServiceConfiguration](https://gist.github.com/duc12597/84e6707688f2caca9a85241b85e2846f#file-powerauthwebserviceconfiguration-java) and [PowerAuthSOAP](https://gist.github.com/duc12597/84e6707688f2caca9a85241b85e2846f#file-powerauthsoap-java).

Perhaps my data was not correctly encoded? Any help would be much appreciated.

**Comment by romanstrobl** [comment]
Looking at your code, I noticed you call:
```
String KEY_EPH_PUBLIC_STR = base64.encode(KEY_EPH_PUBLIC.getEncoded());
```

I think that this line causes the problem, because the key bytes are not in the format expected by PowerAuth server. The generated keypair is an ECDH(secp256r1) keypair and call the `getEncoded()` call will return different bytes than expected by PowerAuth server.

Furthermore this line is a bit strange:
```
KeyPair ephKeyPair = activation.generateDeviceKeyPair();
```

The ephemeral keypair is not a device keypair - it is a bit misleading to use the `generateDeviceKeyPair()` method for this use case.

Please use the following code instead for generating the emphemeral keypair and converting the public key:
```
KeyPair ephemeralKeyPair = keygen.generateKeyPair();
byte[] ephemeralPublicKeyBytes = util.convertPublicKeyToBytes(eEphemeralKeyPair.getPublic());
prepareReq.setEphemeralPublicKey(BaseEncoding.base64().encode(ephemeralPublicKeyBytes));
```

Let me know if this change resolved the issue, otherwise I will investigate more.

**Comment by duc12597** [comment]
Thank you so much that was exactly the problem.
Should another problem arises that I cannot resolve, I will open another issue.
Again thank you for your assistant.

**Comment by romanstrobl** [comment]
Glad I could help. I am closing the issue.

**Comment by petrdvorak** [comment]
@duc12597 Hello Duc, glad you managed to resolve the issue.

Could I please ask you to contact us at hello@powerauth.com to discuss your PowerAuth use case, and possibility of commercial support and our licensing options (PowerAuth is licensed under AGPLv3 and software users should adhere to terms of this license).

**Comment by duc12597** [comment]
Thank you for your offer, I'm using PowerAuth on a school project and don't plan to use it for commercial use.

**Comment by petrdvorak** [comment]
@duc12597 This is great as well! :) In this case, do not hesitate to contact us at the same e-mail address in case you need any further help. We would like your school project to be a success!
