### ISSUE TITLE
Add application platform during activation

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#352]
Currently, we do not store platform with the activation and it could be useful to have it...

**Comment by petrdvorak** [comment]
We should also consider what we want to collect:

- Platform (iOS, Android, HW token)?
- Device model (iPhone XS, Samsung Galaxy X, ...) => how to normalize? Probably just description?

**Comment by hvge** [comment]
I would use simple semicolon separated string, `{platform};{device-model-id}`. For example:
- `ios;iPhone12,3` (e.g. iPhone 11 Pro)
- `android;SM-G973F` (e.g. Samsung Galaxy S10)
- `mac;MacBookPro11,3` (e.g. MacBook Pro, Retina, 15-ich, Late 2013, running at Mac Catalyst)
- `hw;mk1` (e.g. some HW token...)

The reason for that is that in the mobile SDK, we don't know the real device name, like "iPhone 11 Pro". We know just the platform specific identifier, which may vary between the platforms. For example, here's some [translation table for Android](https://github.com/jaredrummler/AndroidDeviceNames/blob/master/json/devices.json). As you can see, it's very space consuming :)

**Comment by romanstrobl** [comment]
Ok, let's do it this way, we can easily extend this string in future if needed. I will update the `ActivationLayer2Request` to contain the device info, e.g.:
```
{
  "devicePublicKey": "MIIxs...",
  "activationName": "My iPhone",
  "extras": "",
  "deviceInfo": "ios;iPhone12,3"
}
```

**Comment by romanstrobl** [comment]
We'll need to separate the platform parameter due to its significance, so the `ActivationLayer2Request` will look like this:
{
  "devicePublicKey": "MIIxs...",
  "activationName": "My iPhone",
  "extras": "",
  "platform": "ios",
  "deviceInfo": "iPhone12,3"
}

The `platform` enum will allow following values:
- `ios`
- `android`
- `hw`
- `unknown` (e.g. cmd-tool or old activations)

The `deviceInfo` String will contain device model ID for now, but can be easily extended as it is a free form string.
