### ISSUE TITLE
Value uniqueness does not take type into account

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#969]
Currently, we use only unique value for uniqueness check: https://github.com/wultra/powerauth-server/blob/d4d09f91a0808b3053c731f3b28d6e1e6d7dfd6e/powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/UniqueValueEntity.java

We should also guard it according to the type. With current implementation, we may be overly restrictive in finding a unique value.

**Comment by romanstrobl** [comment]
The unique value type is only informational. This change would have a slight performance impact, because unique indexes over mutliple columns are slower than a single unique index over a primary key column. I suggest we close the issue, or include the type in the `unique_value` as 1 extra character, if we really want to include it, however it is just metadata.
